Update latex.yml

diff --git a/.github/workflows/latex.yml b/.github/workflows/latex.yml
--- a/.github/workflows/latex.yml
+++ b/.github/workflows/latex.yml
@@ -34,28 +34,23 @@ jobs:
         git commit -m "Update CV.pdf"
 
         # Fetch and merge remote changes before pushing
-        git pull origin main --rebase || echo "Merge failed, proceed with rebase" # Optional: Rebase before merge to avoid conflicts
+        git pull origin main --rebase || echo "Merge failed, proceed with rebase"  # Optional: Rebase before merge to avoid conflicts
         git push origin main
 
-    - name: Debug Repository Access
-      env:
-        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
+    - name: Set up SSH for GitHub Actions
       run: |
-        git remote add test-repo https://x-access-token:${GITHUB_TOKEN}@github.com/nsswifter/AcademicApplicationDocuments.git || true
-        git ls-remote test-repo || echo "Failed to access repository"
+        mkdir -p ~/.ssh
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        ssh-keyscan github.com >> ~/.ssh/known_hosts
 
-    - name: Add Remote if Not Exists
-      env:
-        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
+    - name: Add Remote for Private Repository
       run: |
-        if ! git remote get-url private-repo; then
-          git remote add private-repo https://x-access-token:${GITHUB_TOKEN}@github.com/nsswifter/AcademicApplicationDocuments.git
-        fi
+        git remote add private-repo git@github.com:nsswifter/AcademicApplicationDocuments.git
 
     - name: Merge changes with private repository
-      env:
-        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT }}
       run: |
+        # Fetch the latest changes from the private repo
         git fetch private-repo
         git checkout main
         git merge private-repo/main --allow-unrelated-histories
